/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/DioramaBlenderTextures.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function DioramaBlenderTextures(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/DioramaBlenderTextures.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Estanteria_Low" geometry={nodes.Estanteria_Low.geometry} material={materials['Material #25']} position={[1.844, -36.762, -20.35]} scale={0.382} />
        <mesh name="Pared_low" geometry={nodes.Pared_low.geometry} material={materials['Material #25']} position={[23.706, -36.762, -9.897]} scale={0.382} />
        <mesh name="Suelo_low" geometry={nodes.Suelo_low.geometry} material={materials['Material #25']} position={[7.125, -65.541, -10.684]} scale={0.382} />
        <mesh name="TablonSuelo_low" geometry={nodes.TablonSuelo_low.geometry} material={materials['Material #25']} position={[-10.918, -65.541, 1.682]} scale={[0.365, 0.382, 0.333]} />
        <mesh name="Maquina_low" geometry={nodes.Maquina_low.geometry} material={materials['Material #25']} position={[-0.29, -57.405, -23.252]} scale={[0.251, 0.278, 0.242]} />
        <mesh name="Columna_low" geometry={nodes.Columna_low.geometry} material={materials['Material #25']} position={[11.394, -65.291, -27.47]} scale={[0.382, 0.382, 0.349]} />
        <mesh name="TablonSuelo_low001" geometry={nodes.TablonSuelo_low001.geometry} material={materials['Material #25']} position={[-10.918, -65.541, -1.516]} scale={[0.365, 0.382, 0.333]} />
        <mesh name="TablonSuelo_low002" geometry={nodes.TablonSuelo_low002.geometry} material={materials['Material #25']} position={[-10.918, -65.541, -4.714]} scale={[0.365, 0.382, 0.333]} />
        <mesh name="TablonSuelo_low003" geometry={nodes.TablonSuelo_low003.geometry} material={materials['Material #25']} position={[-10.918, -65.541, -7.542]} scale={[0.365, 0.382, 0.333]} />
        <mesh name="TablonSuelo_low004" geometry={nodes.TablonSuelo_low004.geometry} material={materials['Material #25']} position={[-10.918, -65.541, -10.364]} scale={[0.365, 0.382, 0.333]} />
        <mesh name="TablonSuelo_low005" geometry={nodes.TablonSuelo_low005.geometry} material={materials['Material #25']} position={[-10.918, -65.541, -13.186]} scale={[0.365, 0.382, 0.333]} />
        <mesh name="TablonSuelo_low006" geometry={nodes.TablonSuelo_low006.geometry} material={materials['Material #25']} position={[-10.918, -65.541, -16.008]} scale={[0.365, 0.382, 0.333]} />
        <mesh name="TablonSuelo_low007" geometry={nodes.TablonSuelo_low007.geometry} material={materials['Material #25']} position={[-10.918, -65.541, -18.835]} scale={[0.365, 0.382, 0.333]} />
        <mesh name="TablonSuelo_low008" geometry={nodes.TablonSuelo_low008.geometry} material={materials['Material #25']} position={[-10.918, -65.541, -21.661]} scale={[0.365, 0.382, 0.333]} />
        <mesh name="TablonSuelo_low009" geometry={nodes.TablonSuelo_low009.geometry} material={materials['Material #25']} position={[-10.918, -65.541, -24.491]} scale={[0.365, 0.382, 0.333]} />
        <mesh name="TablonSuelo_low010" geometry={nodes.TablonSuelo_low010.geometry} material={materials['Material #25']} position={[-10.918, -65.541, -27.317]} scale={[0.365, 0.382, 0.333]} />
        <mesh name="Cubo_low" geometry={nodes.Cubo_low.geometry} material={materials['Material #25']} position={[2.063, -48.604, -27.153]} scale={[0.299, 0.299, 0.272]} />
        <mesh name="Piramide_low" geometry={nodes.Piramide_low.geometry} material={materials['Material #25']} position={[6.507, -48.581, -26.759]} scale={[0.33, 0.33, 0.301]} />
        <mesh name="Mesa_low" geometry={nodes.Mesa_low.geometry} material={materials['Material #25']} position={[13.257, -59.124, -11.606]} scale={0.382} />
        <mesh name="Camara_low" geometry={nodes.Camara_low.geometry} material={materials['Material #25']} position={[8.178, -54.394, -18.437]} rotation={[0, -0.175, 0]} scale={[0.277, 0.277, 0.253]} />
        <mesh name="CamaPerro_low" geometry={nodes.CamaPerro_low.geometry} material={materials['Material #25']} position={[20.499, -65.086, -2.809]} rotation={[0, 0.087, 0]} scale={[0.298, 0.326, 0.298]} />
        <mesh name="Maceta_low" geometry={nodes.Maceta_low.geometry} material={materials['Material #25']} position={[21.769, -64.825, -22.104]} scale={[0.429, 0.269, 0.429]} />
        <mesh name="Sillon_low" geometry={nodes.Sillon_low.geometry} material={materials['Material #25']} position={[18.236, -59.124, -11.606]} scale={0.382} />
        <mesh name="Estanteria_low" geometry={nodes.Estanteria_low.geometry} material={materials['Material #25']} position={[1.844, -36.579, -20.35]} rotation={[Math.PI / 2, 0, 0]} scale={[0.365, 0.333, 0.382]} />
        <mesh name="Estanteria_02_low" geometry={nodes.Estanteria_02_low.geometry} material={materials['Material #25']} position={[1.844, -36.762, -20.35]} rotation={[Math.PI / 2, 0, 0]} scale={[0.365, 0.333, 0.382]} />
        <mesh name="Cactus_low" geometry={nodes.Cactus_low.geometry} material={materials['Material #25']} position={[21.808, -62.615, -22.156]} rotation={[0, -Math.PI / 4, 0]} scale={[0.46, 0.61, 0.46]} />
        <mesh name="RuedasSillon_low" geometry={nodes.RuedasSillon_low.geometry} material={materials['Material #25']} position={[17.481, -64.012, -10.459]} scale={0.382} />
        <mesh name="Patas_camara_low" geometry={nodes.Patas_camara_low.geometry} material={materials['Material #25']} position={[12.084, -58.289, -21.616]} rotation={[Math.PI / 2, 0, Math.PI / 9]} scale={0.382} />
        <mesh name="Alfiombra_low" geometry={nodes.Alfiombra_low.geometry} material={materials['Material #25']} position={[5.618, -65.138, -10.684]} scale={0.382} />
        <mesh name="CollarPerro_low" geometry={nodes.CollarPerro_low.geometry} material={materials['Material #25']} position={[17.492, -62.173, -2.829]} scale={0.382} />
        <mesh name="BrazosSillon_low" geometry={nodes.BrazosSillon_low.geometry} material={materials['Material #25']} position={[18.407, -58.881, -9.613]} rotation={[0, -1.571, 0]} scale={[0.279, 0.306, 0.306]} />
        <mesh name="PataMesa_low" geometry={nodes.PataMesa_low.geometry} material={materials['Material #25']} position={[10.376, -65.206, -5.958]} scale={[0.284, 0.386, 0.284]} />
        <mesh name="BaseOrdenador_low" geometry={nodes.BaseOrdenador_low.geometry} material={materials['Material #25']} position={[11.845, -58.925, -11.606]} scale={[0.382, 0.56, 0.473]} />
        <mesh name="PantallaOrdenador_low" geometry={nodes.PantallaOrdenador_low.geometry} material={materials['Material #25']} position={[11.66, -56.316, -11.606]} scale={0.382} />
        <mesh name="Teclado_low" geometry={nodes.Teclado_low.geometry} material={materials['Material #25']} position={[14.114, -58.772, -11.606]} scale={0.382} />
        <mesh name="AlfombraRaton_low" geometry={nodes.AlfombraRaton_low.geometry} material={materials['Material #25']} position={[13.257, -58.833, -15.654]} scale={0.382} />
        <mesh name="Cascos_low" geometry={nodes.Cascos_low.geometry} material={materials['Material #25']} position={[10.865, -56.495, -8.817]} rotation={[1.382, 0.159, 1.658]} scale={0.837} />
        <mesh name="Raton_low" geometry={nodes.Raton_low.geometry} material={materials['Material #25']} position={[12.744, -58.821, -15.317]} scale={[0.382, 0.382, 0.497]} />
        <mesh name="PataMesa_low001" geometry={nodes.PataMesa_low001.geometry} material={materials['Material #25']} position={[16.055, -65.206, -5.958]} scale={[0.284, 0.386, 0.284]} />
        <mesh name="PataMesa_low002" geometry={nodes.PataMesa_low002.geometry} material={materials['Material #25']} position={[10.376, -65.206, -17.251]} scale={[0.284, 0.386, 0.284]} />
        <mesh name="PataMesa_low003" geometry={nodes.PataMesa_low003.geometry} material={materials['Material #25']} position={[16.055, -65.206, -17.251]} scale={[0.284, 0.386, 0.284]} />
        <mesh name="CristalMaquina_low" geometry={nodes.CristalMaquina_low.geometry} material={materials['Material #25']} position={[-0.29, -57.47, -22.284]} rotation={[-0.175, 0, 0]} scale={[0.251, 0.278, 0.242]} />
        <mesh name="BotonMaquina_low" geometry={nodes.BotonMaquina_low.geometry} material={materials['Material #25']} position={[-1.378, -56.613, -21.294]} rotation={[0.436, 0, 0]} scale={0.261} />
        <mesh name="BotonMaquina_low001" geometry={nodes.BotonMaquina_low001.geometry} material={materials['Material #25']} position={[-0.313, -56.613, -21.294]} rotation={[0.436, 0, 0]} scale={0.261} />
        <mesh name="BotonMaquina_low002" geometry={nodes.BotonMaquina_low002.geometry} material={materials['Material #25']} position={[2.649, -56.613, -21.294]} rotation={[0.436, 0, 0]} scale={0.261} />
        <mesh name="Joistick_low" geometry={nodes.Joistick_low.geometry} material={materials['Material #25']} position={[0.961, -56.435, -21.234]} rotation={[0.436, 0, 0]} scale={0.258} />
        <mesh name="Tragaperras_low" geometry={nodes.Tragaperras_low.geometry} material={materials['Material #25']} position={[0.646, -58.658, -20.079]} rotation={[Math.PI / 2, 0, 0]} scale={0.382} />
        <mesh name="BotonnnMaqu_low" geometry={nodes.BotonnnMaqu_low.geometry} material={materials['Material #25']} position={[1.294, -58.658, -20.326]} rotation={[Math.PI / 2, 0, 0]} scale={0.382} />
        <mesh name="MangoCamara_low" geometry={nodes.MangoCamara_low.geometry} material={materials['Material #25']} position={[10.155, -53.386, -22.04]} scale={0.382} />
        <mesh name="Patin_low" geometry={nodes.Patin_low.geometry} material={materials['Material #25']} position={[3.803, -63.958, -5.555]} scale={0.382} />
        <mesh name="RuedaPatin_low" geometry={nodes.RuedaPatin_low.geometry} material={materials['Material #25']} position={[3.685, -64.734, -2.794]} rotation={[Math.PI / 2, 0, 1.222]} scale={0.572} />
        <mesh name="RuedaPatin_low001" geometry={nodes.RuedaPatin_low001.geometry} material={materials['Material #25']} position={[3.858, -64.734, -8.441]} rotation={[Math.PI / 2, 0, -1.92]} scale={0.572} />
        <mesh name="RuedaPatin_low002" geometry={nodes.RuedaPatin_low002.geometry} material={materials['Material #25']} position={[1.891, -64.734, -7.725]} rotation={[Math.PI / 2, 0, 1.222]} scale={0.572} />
        <mesh name="RuedaPatin_low003" geometry={nodes.RuedaPatin_low003.geometry} material={materials['Material #25']} position={[5.653, -64.734, -3.51]} rotation={[Math.PI / 2, 0, -1.92]} scale={0.572} />
        <mesh name="TablonSuelo_low011" geometry={nodes.TablonSuelo_low011.geometry} material={materials['Material #25']} position={[-10.918, -65.541, -29.566]} scale={[0.365, 0.382, 0.333]} />
        <mesh name="PerroO_low" geometry={nodes.PerroO_low.geometry} material={materials['Material #25']} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Diadema_low" geometry={nodes.Diadema_low.geometry} material={materials['Material #25']} position={[18.307, -62.188, -2.83]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.382} />
        <mesh name="Orejas_low001" geometry={nodes.Orejas_low001.geometry} material={materials['Material #25']} position={[18.307, -61.166, -2.83]} scale={0.382} />
      </group>
    </group>
  )
}

useGLTF.preload('/DioramaBlenderTextures.glb')
