/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/Diorama_high.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Diorama_high.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.035, -0.018, -0.303]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Estanteria_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.063, -0.76, -0.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Alfiombra_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.263, -0.595, -0.18]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.AlfombraRaton_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.226, -0.597, -0.074]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1.236, 1.465]}>
        <mesh geometry={nodes.BaseOrdenador_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.12, -0.537, -0.327]} rotation={[-1.134, 0, 0]} scale={0.683}>
        <mesh geometry={nodes.BotonMaquina_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.092, -0.537, -0.327]} rotation={[-1.134, 0, 0]} scale={0.683}>
        <mesh geometry={nodes.Obj_BotonMaquina_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.014, -0.537, -0.327]} rotation={[-1.134, 0, 0]} scale={0.683}>
        <mesh geometry={nodes.Obj_BotonMaquina_high_1.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.05, -0.59, -0.302]}>
        <mesh geometry={nodes.BotonnnMaqu_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.398, -0.596, -0.022]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.729, 0.799, 0.799]}>
        <mesh geometry={nodes.BrazosSillon_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.487, -0.694, -0.35]} rotation={[-Math.PI / 2, 0, -Math.PI / 4]} scale={[1.203, 1.203, 1.594]}>
        <mesh geometry={nodes.Cactus_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.452, -0.758, 0.156]} rotation={[-Math.PI / 2, 0, 0.087]} scale={[0.78, 0.778, 0.853]}>
        <mesh geometry={nodes.CamaPerro_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.13, -0.479, -0.253]} rotation={[-Math.PI / 2, 0, -0.175]} scale={[0.726, 0.662, 0.726]}>
        <mesh geometry={nodes.Camara_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.201, -0.534, -0.001]} rotation={[1.886, -1.39, 2.068]} scale={2.188}>
        <mesh geometry={nodes.Cascos_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.374, -0.682, 0.155]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CollarPerro_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.214, -0.764, -0.489]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.912, 1]}>
        <mesh geometry={nodes.Columna_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.091, -0.559, -0.353]} rotation={[-1.745, 0, 0]} scale={[0.657, 0.633, 0.727]}>
        <mesh geometry={nodes.CristalMaquina_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.03, -0.327, -0.481]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.781, 0.712, 0.781]}>
        <mesh geometry={nodes.Cubo_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.035, -0.018, -0.303]} scale={[0.955, 1, 0.871]}>
        <mesh geometry={nodes.Estanteria_02_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.035, -0.013, -0.303]} scale={[0.955, 1, 0.871]}>
        <mesh geometry={nodes.Obj_Estanteria_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.058, -0.532, -0.326]} rotation={[-1.134, 0, 0]} scale={0.674}>
        <mesh geometry={nodes.Joistick_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.486, -0.751, -0.349]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.122, 1.122, 0.703]}>
        <mesh geometry={nodes.Maceta_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.182, -0.452, -0.347]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.MangoCamara_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.091, -0.557, -0.379]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.657, 0.633, 0.727]}>
        <mesh geometry={nodes.Maquina_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.263, -0.602, -0.074]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesa_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.221, -0.529, -0.074]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.PantallaOrdenador_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.536, -0.018, -0.029]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Pared_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.336, -0.761, -0.222]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.742, 0.742, 1.009]}>
        <mesh geometry={nodes.PataMesa_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.336, -0.761, 0.074]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.742, 0.742, 1.009]}>
        <mesh geometry={nodes.Obj_PataMesa_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.188, -0.761, -0.222]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.742, 0.742, 1.009]}>
        <mesh geometry={nodes.Obj_PataMesa_high_1.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.188, -0.761, 0.074]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.742, 0.742, 1.009]}>
        <mesh geometry={nodes.Obj_PataMesa_high_2.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.232, -0.581, -0.336]} rotation={[0, -Math.PI / 9, 0]}>
        <mesh geometry={nodes.Patas_camara_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.016, -0.729, 0.084]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Patin_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.087, -0.327, -0.47]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.863, 0.787, 0.863]}>
        <mesh geometry={nodes.Piramide_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.25, -0.594, -0.171]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1.3, 1]}>
        <mesh geometry={nodes.Raton_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.064, -0.749, 0.138]} rotation={[-Math.PI, 1.222, Math.PI]} scale={1.497}>
        <mesh geometry={nodes.RuedaPatin_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.034, -0.749, 0.027]} rotation={[0, -1.222, 0]} scale={1.497}>
        <mesh geometry={nodes.Obj_RuedaPatin_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.013, -0.749, 0.156]} rotation={[0, -1.222, 0]} scale={1.511}>
        <mesh geometry={nodes.Obj_RuedaPatin_high_1.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.017, -0.749, 0.009]} rotation={[-Math.PI, 1.222, Math.PI]} scale={1.497}>
        <mesh geometry={nodes.Obj_RuedaPatin_high_2.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.374, -0.73, -0.044]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.RuedasSillon_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.103, -0.77, -0.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Suelo_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.369, -0.77, 0.19]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]}>
        <mesh geometry={nodes.TablonSuelo_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.369, -0.77, 0.106]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]}>
        <mesh geometry={nodes.Obj_TablonSuelo_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.369, -0.77, -0.485]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]}>
        <mesh geometry={nodes.Obj_TablonSuelo_high_1.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.369, -0.77, 0.273]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]}>
        <mesh geometry={nodes.Obj_TablonSuelo_high_2.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.369, -0.77, -0.544]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]}>
        <mesh geometry={nodes.Obj_TablonSuelo_high_3.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.369, -0.77, -0.337]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]}>
        <mesh geometry={nodes.Obj_TablonSuelo_high_4.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.369, -0.77, -0.189]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]}>
        <mesh geometry={nodes.Obj_TablonSuelo_high_5.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.369, -0.77, -0.411]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]}>
        <mesh geometry={nodes.Obj_TablonSuelo_high_6.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.369, -0.77, -0.263]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]}>
        <mesh geometry={nodes.Obj_TablonSuelo_high_7.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.369, -0.77, -0.042]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]}>
        <mesh geometry={nodes.Obj_TablonSuelo_high_8.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.369, -0.77, -0.115]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]}>
        <mesh geometry={nodes.Obj_TablonSuelo_high_9.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.286, -0.593, -0.074]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Teclado_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.067, -0.59, -0.296]}>
        <mesh geometry={nodes.Tragaperras_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[-0.369, -0.77, 0.032]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]}>
        <mesh geometry={nodes.Obj_TablonSuelo_high_10.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.393, -0.602, -0.074]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Sillon_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.395, -0.656, 0.155]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Orejas_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <group position={[0.395, -0.682, 0.155]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Diadema_high.geometry} material={materials['fallback Material']} scale={0.01} />
      </group>
      <mesh geometry={nodes.PerroO_high.geometry} material={materials['fallback Material']} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/Diorama_high.glb')
