/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/DioramaTexturesTest.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelTextures(props) {
  const { nodes, materials } = useGLTF('/DioramaTexturesTest.glb')
  return (
    <group {...props} dispose={null} scale={0.01}>
      <mesh geometry={nodes.Estanteria_Low.geometry} material={materials['fallback Material']} position={[-3.531, -1.76, -30.273]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Pared_low.geometry} material={materials['fallback Material']} position={[53.634, -1.76, -2.941]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Suelo_low.geometry} material={materials['fallback Material']} position={[10.276, -77.011, -4.999]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.TablonSuelo_low.geometry} material={materials['fallback Material']} position={[-36.904, -77.011, 27.338]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]} />
      <mesh geometry={nodes.Maquina_low.geometry} material={materials['fallback Material']} position={[-9.111, -55.738, -37.861]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.657, 0.633, 0.727]} />
      <mesh geometry={nodes.Columna_low.geometry} material={materials['fallback Material']} position={[21.439, -76.36, -48.889]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.912, 1]} />
      <mesh geometry={nodes.Obj_TablonSuelo_low.geometry} material={materials['fallback Material']} position={[-36.904, -77.011, 18.976]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]} />
      <mesh geometry={nodes.Obj_TablonSuelo_low_1.geometry} material={materials['fallback Material']} position={[-36.904, -77.011, 10.613]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]} />
      <mesh geometry={nodes.Obj_TablonSuelo_low_2.geometry} material={materials['fallback Material']} position={[-36.904, -77.011, 3.217]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]} />
      <mesh geometry={nodes.Obj_TablonSuelo_low_3.geometry} material={materials['fallback Material']} position={[-36.904, -77.011, -4.162]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]} />
      <mesh geometry={nodes.Obj_TablonSuelo_low_4.geometry} material={materials['fallback Material']} position={[-36.904, -77.011, -11.541]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]} />
      <mesh geometry={nodes.Obj_TablonSuelo_low_5.geometry} material={materials['fallback Material']} position={[-36.904, -77.011, -18.92]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]} />
      <mesh geometry={nodes.Obj_TablonSuelo_low_6.geometry} material={materials['fallback Material']} position={[-36.904, -77.011, -26.312]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]} />
      <mesh geometry={nodes.Obj_TablonSuelo_low_7.geometry} material={materials['fallback Material']} position={[-36.904, -77.011, -33.701]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]} />
      <mesh geometry={nodes.Obj_TablonSuelo_low_8.geometry} material={materials['fallback Material']} position={[-36.904, -77.011, -41.1]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]} />
      <mesh geometry={nodes.Obj_TablonSuelo_low_9.geometry} material={materials['fallback Material']} position={[-36.904, -77.011, -48.489]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]} />
      <mesh geometry={nodes.Cubo_low.geometry} material={materials['fallback Material']} position={[-2.958, -32.726, -48.062]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.781, 0.712, 0.781]} />
      <mesh geometry={nodes.Piramide_low.geometry} material={materials['fallback Material']} position={[8.662, -32.664, -47.032]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.863, 0.787, 0.863]} />
      <mesh geometry={nodes.Mesa_low.geometry} material={materials['fallback Material']} position={[26.311, -60.233, -7.409]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Camara_low.geometry} material={materials['fallback Material']} position={[13.03, -47.866, -25.27]} rotation={[-Math.PI / 2, 0, -0.175]} scale={[0.726, 0.662, 0.726]} />
      <mesh geometry={nodes.CamaPerro_low.geometry} material={materials['fallback Material']} position={[45.247, -75.823, 15.594]} rotation={[-Math.PI / 2, 0, 0.087]} scale={[0.78, 0.778, 0.853]} />
      <mesh geometry={nodes.Maceta_low.geometry} material={materials['fallback Material']} position={[48.569, -75.141, -34.858]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.122, 1.122, 0.703]} />
      <mesh geometry={nodes.Sillon_low.geometry} material={materials['fallback Material']} position={[39.33, -60.233, -7.409]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Estanteria_low.geometry} material={materials['fallback Material']} position={[-3.531, -1.282, -30.273]} scale={[0.955, 1, 0.871]} />
      <mesh geometry={nodes.Estanteria_02_low.geometry} material={materials['fallback Material']} position={[-3.531, -1.76, -30.273]} scale={[0.955, 1, 0.871]} />
      <mesh geometry={nodes.Cactus_low.geometry} material={materials['fallback Material']} position={[48.672, -69.362, -34.996]} rotation={[-Math.PI / 2, 0, -Math.PI / 4]} scale={[1.203, 1.203, 1.594]} />
      <mesh geometry={nodes.RuedasSillon_low.geometry} material={materials['fallback Material']} position={[37.357, -73.014, -4.411]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Patas_camara_low.geometry} material={materials['fallback Material']} position={[23.245, -58.051, -33.582]} rotation={[0, -Math.PI / 9, 0]} />
      <mesh geometry={nodes.Alfiombra_low.geometry} material={materials['fallback Material']} position={[6.338, -75.958, -4.999]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.CollarPerro_low.geometry} material={materials['fallback Material']} position={[37.385, -68.206, 15.541]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BrazosSillon_low.geometry} material={materials['fallback Material']} position={[39.779, -59.598, -2.196]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.729, 0.799, 0.799]} />
      <mesh geometry={nodes.PataMesa_low.geometry} material={materials['fallback Material']} position={[18.779, -76.137, 7.36]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.742, 0.742, 1.009]} />
      <mesh geometry={nodes.BaseOrdenador_low.geometry} material={materials['fallback Material']} position={[22.619, -59.713, -7.409]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1.236, 1.465]} />
      <mesh geometry={nodes.PantallaOrdenador_low.geometry} material={materials['fallback Material']} position={[22.135, -52.891, -7.409]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Teclado_low.geometry} material={materials['fallback Material']} position={[28.553, -59.313, -7.409]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.AlfombraRaton_low.geometry} material={materials['fallback Material']} position={[26.311, -59.473, -17.993]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cascos_low.geometry} material={materials['fallback Material']} position={[20.057, -53.359, -0.117]} rotation={[1.886, -1.39, 2.068]} scale={2.188} />
      <mesh geometry={nodes.Raton_low.geometry} material={materials['fallback Material']} position={[24.969, -59.44, -17.113]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1.3, 1]} />
      <mesh geometry={nodes.Obj_PataMesa_low.geometry} material={materials['fallback Material']} position={[33.629, -76.137, 7.36]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.742, 0.742, 1.009]} />
      <mesh geometry={nodes.Obj_PataMesa_low_1.geometry} material={materials['fallback Material']} position={[18.779, -76.137, -22.17]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.742, 0.742, 1.009]} />
      <mesh geometry={nodes.Obj_PataMesa_low_2.geometry} material={materials['fallback Material']} position={[33.629, -76.137, -22.17]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.742, 0.742, 1.009]} />
      <mesh geometry={nodes.CristalMaquina_low.geometry} material={materials['fallback Material']} position={[-9.111, -55.908, -35.33]} rotation={[-1.745, 0, 0]} scale={[0.657, 0.633, 0.727]} />
      <mesh geometry={nodes.BotonMaquina_low.geometry} material={materials['fallback Material']} position={[-11.957, -53.667, -32.741]} rotation={[-1.134, 0, 0]} scale={0.683} />
      <mesh geometry={nodes.Obj_BotonMaquina_low.geometry} material={materials['fallback Material']} position={[-9.171, -53.667, -32.741]} rotation={[-1.134, 0, 0]} scale={0.683} />
      <mesh geometry={nodes.Obj_BotonMaquina_low_1.geometry} material={materials['fallback Material']} position={[-1.427, -53.667, -32.741]} rotation={[-1.134, 0, 0]} scale={0.683} />
      <mesh geometry={nodes.Joistick_low.geometry} material={materials['fallback Material']} position={[-5.841, -53.202, -32.585]} rotation={[-1.134, 0, 0]} scale={0.674} />
      <mesh geometry={nodes.Tragaperras_low.geometry} material={materials['fallback Material']} position={[-6.664, -59.015, -29.564]} />
      <mesh geometry={nodes.BotonnnMaqu_low.geometry} material={materials['fallback Material']} position={[-4.969, -59.015, -30.211]} />
      <mesh geometry={nodes.MangoCamara_low.geometry} material={materials['fallback Material']} position={[18.2, -45.229, -34.692]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Patin_low.geometry} material={materials['fallback Material']} position={[1.592, -72.874, 8.414]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.RuedaPatin_low.geometry} material={materials['fallback Material']} position={[1.283, -74.904, 15.633]} rotation={[0, -1.222, 0]} scale={1.497} />
      <mesh geometry={nodes.Obj_RuedaPatin_low.geometry} material={materials['fallback Material']} position={[1.734, -74.904, 0.866]} rotation={[-Math.PI, 1.222, Math.PI]} scale={1.497} />
      <mesh geometry={nodes.Obj_RuedaPatin_low_1.geometry} material={materials['fallback Material']} position={[-3.41, -74.904, 2.738]} rotation={[0, -1.222, 0]} scale={1.497} />
      <mesh geometry={nodes.Obj_RuedaPatin_low_2.geometry} material={materials['fallback Material']} position={[6.427, -74.904, 13.761]} rotation={[-Math.PI, 1.222, Math.PI]} scale={1.497} />
      <mesh geometry={nodes.Obj_TablonSuelo_low_10.geometry} material={materials['fallback Material']} position={[-36.904, -77.011, -54.372]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.955, 0.871, 1]} />
      <mesh geometry={nodes.PerroO_low.geometry} material={materials['fallback Material']} />
      <mesh geometry={nodes.Diadema_low.geometry} material={materials['fallback Material']} position={[39.517, -68.246, 15.538]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Orejas_low001.geometry} material={materials['fallback Material']} position={[39.516, -65.572, 15.538]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/DioramaTexturesTest.glb')
