/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/JarronBlender.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./JarronBlender.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Jarron_low.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={[0.13, 0.13, 0.225]} />
    </group>
  )
}

useGLTF.preload('./JarronBlender.glb')
