/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/MesaBlender.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./MesaBlender.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesa_low.geometry} material={materials['Material #25']} position={[26.311, -60.233, -7.409]} />
      <mesh geometry={nodes.PataMesa_low.geometry} material={materials['Material #25']} position={[18.779, -76.137, 7.36]} scale={[0.742, 1.009, 0.742]} />
      <mesh geometry={nodes.PataMesa_low001.geometry} material={materials['Material #25']} position={[33.629, -76.137, 7.36]} scale={[0.742, 1.009, 0.742]} />
      <mesh geometry={nodes.PataMesa_low002.geometry} material={materials['Material #25']} position={[18.779, -76.137, -22.17]} scale={[0.742, 1.009, 0.742]} />
      <mesh geometry={nodes.PataMesa_low003.geometry} material={materials['Material #25']} position={[33.629, -76.137, -22.17]} scale={[0.742, 1.009, 0.742]} />
    </group>
  )
}

useGLTF.preload('./MesaBlender.glb')
